/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_speechoo_coruja_CorujaJNI */

#ifndef _Included_org_speechoo_coruja_CorujaJNI
#define _Included_org_speechoo_coruja_CorujaJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_speechoo_coruja_CorujaJNI
 * Method:    enableDictation
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_speechoo_coruja_CorujaJNI_enableDictation
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_speechoo_coruja_CorujaJNI
 * Method:    startSREngine
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_speechoo_coruja_CorujaJNI_startSREngine
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_speechoo_coruja_CorujaJNI
 * Method:    stopSREngine
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_speechoo_coruja_CorujaJNI_stopSREngine
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
